version: '3.8'

services:
  backend:
    image: chaerytonic/medisave-backen:latest
    container_name: backend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: ["java", "-jar", "backend-0.0.1-SNAPSHOT.jar"]
    networks:
      - medisave

  frontend:
    build: ./react
    container_name: react
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - medisave
    # volumes:
    #   - build-data:/app/build  # 공유 볼륨에 빌드 결과 저장
    # command: ["npm", "run", "build"]

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./react/nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일
  #     - build-data:/usr/share/nginx/html  # 공유 볼륨에서 빌드 파일 접근
  #   depends_on:
  #     - frontend

  fastapi:
    build: ./fastapi
    container_name: fastapi
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
      - ./fastapi/iden_img:/app/iden_img
      - ./fastapi/insurance_docs:/app/insurance_docs
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - medisave

networks:
  medisave:
    driver: bridge